# Generated by Django 4.2.1 on 2023-05-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_project_lynk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lynk_preview',
            field=models.URLField(blank=True, null=True, verbose_name='Vista Previa'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lynk',
            field=models.URLField(blank=True, null=True, verbose_name='Dirección Web'),
        ),
    ]
